name: 'Build and upload Component'

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
        description: 'Image tag to build.'
      timestamp:
        required: true
        type: string
        description: 'The build timestamp to be used for binaries.'
      bake_target_name:
        required: true
        type: string
        description: 'Docker Bake target name.'

jobs:
  build-and-upload-artifact:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Cache Docker layers
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        uses: docker/bake-action@7a5dfed3550ca014665af2a27af8fc9d7284b9b3 # v4.5.0
        id: bake
        with:
          targets: ${{ inputs.bake_target_name }}
          set: |
            *.platform=${{ matrix.platform }}
            *.output=type=docker,dest=/tmp/${{ inputs.bake_target_name }}.tar
            *.tags=
            *.cache-to=type=local,dest=/tmp/.buildx-cache
            *.cache-from=type=local,src=/tmp/.buildx-cache
        env:
          VERSION: ${{ inputs.image_tag }}
          BUILD_TIMESTAMP: ${{ inputs.timestamp }}
          COMMIT_HASH: ${{ github.sha }}
          BUILD_OPTS: -tags=exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper

      - name: Save artifacts
        run: |
          mkdir -p /tmp/artifacts
          mv "/tmp/${{ inputs.bake_target_name }}.tar" /tmp/artifacts/
          echo "ARTIFACT_NAME=$(echo \"${{ inputs.bake_target_name }}-${{ inputs.image_tag }}-${{ matrix.platform }}\" | tr '/' '-')" >> $GITHUB_ENV

      - name: Upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp/artifacts/${{ inputs.bake_target_name }}.tar
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true
