name: CI

on:
  pull_request:
  merge_group:

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verification:
    name: Verification
    uses: ./.github/workflows/reusable-verification.yml
    secrets: inherit

  prepare-build:
    needs: verification
    name: Prepare Build
    uses: ./.github/workflows/reusable-prepare-build.yml 

  build:
    needs: prepare-build
    name: Build
    uses: ./.github/workflows/build-and-push-components.yml
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.target) }}
    with:
      image_tag: ${{ format('pr{0}-{1}', github.event.pull_request.number, github.sha) }}
      timestamp: ${{ needs.prepare.outputs.timestamp }}
      bake_target_name: ${{ matrix.target }}

  e2e-docker:
    needs: build
    name: End-to-End Tests on Docker
    uses: ./.github/workflows/reusable-end-to-end-testing.yml
    with:
      image_tag: ${{ format('pr{0}-{1}', github.event.pull_request.number, github.sha) }}
      platform: docker

  e2e-k8s:
    needs: build
    name: End-to-End Tests on Kubernetes
    uses: ./.github/workflows/reusable-end-to-end-testing.yml
    with:
      image_tag: ${{ format('pr{0}-{1}', github.event.pull_request.number, github.sha) }}
      platform: kubernetes

  success:
    # https://github.com/actions/runner/issues/2566
    # https://github.com/actions/toolkit/issues/581
    if: ${{ !cancelled() && !contains(needs.*.result, 'cancelled') && !contains(needs.*.result, 'failure') }}
    needs:
      - build
      - e2e-docker
      - e2e-k8s
    name: Success
    runs-on: ubuntu-latest
    steps:
      - name: Echo Success
        run: |
          echo "::notice Success!"
