name: Main merge
on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  verification:
    name: Verification
    uses: ./.github/workflows/reusable-verification.yml
    secrets: inherit

  prepare-build:
    needs: verification
    name: Prepare Build
    uses: ./.github/workflows/reusable-prepare-build.yml

  build_and_push:
    needs: prepare-build  
    name: Build & Push
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare-build.outputs.targets) }}
    uses: ./.github/workflows/build-and-push-component-release.yml
    with:
      image_name: ghcr.io/wewanttocontributetovmclarity//${{ matrix.target }}
      image_tag: latest
      timestamp: ${{ needs.prepare-build.outputs.timestamp }}
      bake_target_name: ${{ matrix.target }}