name: Verification

on:
  workflow_call:

jobs:
  distributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@3d62d6342d536631db0f577ea353ef0952818281 # v2.4.1

      - name: Run linters for Cloudformation
        run: |
          make lint-cfn

      - name: Run linters for Helm
        run: |
          make gen-helm-docs
          make lint-helm
          [[ -z "$(git status --porcelain)" ]] || exit 1

      - name: Run linters for Azure/Bicep
        run: |
          make gen-bicep
          make lint-bicep
          [[ -z "$(git status --porcelain)" ]] || exit 1

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Lint Github workflows
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          make lint-actions
          echo "::remove-matcher owner=actionlint::"
